version: '3'
services:
  db:
    container_name: db
    image: mysql:8.0
    hostname: VIP
    environment:
      MYSQL_DATABASE: cineshaven
      MYSQL_USER: root123
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlfile/dumpPFGSchema.sql:/docker-entrypoint-initcinesDB.d/dumpPFGSchema.sql
    command: --init-file /docker-entrypoint-initcinesDB.d/dumpPFGSchema.sql

  backend:
    container_name: springbackend
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
